'use strict';

const GAME_STORAGE_KEY = '@Einstein:active-game';


const GAME_TOGGLE_RULE = 'GAME_TOGGLE_RULE';
const GAME_SET = 'GAME_SET';
const GAME_CLEAR = 'GAME_CLEAR';
const GAME_CREATE = 'GAME_CREATE';
const GAME_PAUSE = 'GAME_PAUSE';
const GAME_RESUME = 'GAME_RESUME';

export {
  GAME_SET,
  GAME_CLEAR,
  GAME_CREATE,
  GAME_PAUSE,
  GAME_RESUME,
  GAME_TOGGLE_RULE,

  GAME_STORAGE_KEY
}