'use strict';

const WELCOME_SCREEN_KEY = 'welcome';
const GAME_SCREEN_KEY = 'game';
const HELP_SCREEN_KEY = 'help';

const NAVIGATION_BACK = 'NAVIGATION_BACK';
const NAVIGATION_GAME_NEW = 'NAVIGATION_GAME_NEW';
const NAVIGATION_GAME_CONTINUE = 'NAVIGATION_GAME_CONTINUE';
const NAVIGATION_HELP = 'NAVIGATION_HELP';

export {
  WELCOME_SCREEN_KEY,
  GAME_SCREEN_KEY,
  HELP_SCREEN_KEY,
  NAVIGATION_BACK,
  NAVIGATION_GAME_NEW,
  NAVIGATION_GAME_CONTINUE,
  NAVIGATION_HELP,
}