'use strict';

const WELCOME_SCREEN_KEY = 'welcome';
const GAME_SCREEN_KEY = 'game';
const HELP_SCREEN_KEY = 'help';
const STAT_SCREEN_KEY = 'statistics';

const NAVIGATION_TO_INDEX = 'NAVIGATION_TO_INDEX';
const NAVIGATION_BACK = 'NAVIGATION_BACK';
const NAVIGATION_GAME = 'NAVIGATION_GAME';
const NAVIGATION_HELP = 'NAVIGATION_HELP';
const NAVIGATION_STAT = 'NAVIGATION_STAT';

export {
  WELCOME_SCREEN_KEY,
  GAME_SCREEN_KEY,
  HELP_SCREEN_KEY,
  STAT_SCREEN_KEY,

  NAVIGATION_TO_INDEX,
  NAVIGATION_BACK,
  NAVIGATION_GAME,
  NAVIGATION_HELP,
  NAVIGATION_STAT,
}