'use strict';

const WELCOME_SCREEN_KEY = 'welcome';
const GAME_SCREEN_KEY = 'game';
const HELP_SCREEN_KEY = 'help';

const NAVIGATION_BACK = 'NAVIGATION_BACK';
const NAVIGATION_GAME = 'NAVIGATION_GAME';
const NAVIGATION_HELP = 'NAVIGATION_HELP';

export {
  WELCOME_SCREEN_KEY,
  GAME_SCREEN_KEY,
  HELP_SCREEN_KEY,
  NAVIGATION_BACK,
  NAVIGATION_GAME,
  NAVIGATION_HELP,
}