'use strict';

const PLAYGAME_LEADERBOARD_ID = 'CgkIwoOo3q4YEAIQBg';
const PLAYGAME_ACHIEVEMENT_FIRST_SOLVED = "CgkIwoOo3q4YEAIQAQ";
const PLAYGAME_ACHIEVEMENT_SOLVED_10 = "CgkIwoOo3q4YEAIQAg";
const PLAYGAME_ACHIEVEMENT_SPRINTER = "CgkIwoOo3q4YEAIQAw";
const PLAYGAME_ACHIEVEMENT_MISTAKE_IS_NOT_A_PROBLEM = "CgkIwoOo3q4YEAIQBA";
const PLAYGAME_ACHIEVEMENT_PUZZLE_LOVER = "CgkIwoOo3q4YEAIQBQ";

export {
    PLAYGAME_LEADERBOARD_ID,
    PLAYGAME_ACHIEVEMENT_FIRST_SOLVED,
    PLAYGAME_ACHIEVEMENT_SOLVED_10,
    PLAYGAME_ACHIEVEMENT_SPRINTER,
    PLAYGAME_ACHIEVEMENT_MISTAKE_IS_NOT_A_PROBLEM,
    PLAYGAME_ACHIEVEMENT_PUZZLE_LOVER
}