'use strict';

const PLAYGAMES_LEADERBOARD_ID = 'CgkIwoOo3q4YEAIQBw';
const PLAYGAMES_LEADERBOARD_STACK_ID = 'CgkIwoOo3q4YEAIQCg';
const PLAYGAMES_ACHIEVEMENT_FIRST_SOLVED = "CgkIwoOo3q4YEAIQAQ";
const PLAYGAMES_ACHIEVEMENT_SOLVED_10 = "CgkIwoOo3q4YEAIQAg";
const PLAYGAMES_ACHIEVEMENT_SPRINTER = "CgkIwoOo3q4YEAIQAw";
const PLAYGAMES_ACHIEVEMENT_MISTAKE_IS_NOT_A_PROBLEM = "CgkIwoOo3q4YEAIQBA";
const PLAYGAMES_ACHIEVEMENT_PUZZLE_LOVER = "CgkIwoOo3q4YEAIQBQ";
const PLAYGAMES_ACHIEVEMENT_STRONG_SOLVER = "CgkIwoOo3q4YEAIQCw";

export {
  PLAYGAMES_LEADERBOARD_ID,
  PLAYGAMES_LEADERBOARD_STACK_ID,
  PLAYGAMES_ACHIEVEMENT_FIRST_SOLVED,
  PLAYGAMES_ACHIEVEMENT_SOLVED_10,
  PLAYGAMES_ACHIEVEMENT_SPRINTER,
  PLAYGAMES_ACHIEVEMENT_MISTAKE_IS_NOT_A_PROBLEM,
  PLAYGAMES_ACHIEVEMENT_PUZZLE_LOVER,
  PLAYGAMES_ACHIEVEMENT_STRONG_SOLVER
}