'use strict';

const SETTINGS_STORAGE_KEY = '@Einstein:settings';

const SETTINGS_SET = 'SETTINGS_SET';

const PLAY_GAMES_LOGGED_IN_KEY = 'PLAY_GAMES_LOGGED_IN_KEY';

const OPTION_PRESS_EXCLUDE = 'OPTION_PRESS_EXCLUDE';

const DONT_HIDE_POPUP = 'DONT_HIDE_POPUP';

const LONG_PRESS_SECOND_ACTION = 'LONG_PRESS_SECOND_ACTION';

export {
  SETTINGS_STORAGE_KEY,

  SETTINGS_SET,

  PLAY_GAMES_LOGGED_IN_KEY,

  OPTION_PRESS_EXCLUDE,

  DONT_HIDE_POPUP,

  LONG_PRESS_SECOND_ACTION
};